pipeline:  
  publish:
    image: plugins/docker
    repo: perriea/alpine-telegraf
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tag:
      - latest
      - "3.7"
    when:
      branch: master
      event: 
        - push