################################################################
# Global configuration
################################################################

# Access logs file
accessLogsFile = "/dev/stdout"

# Log level
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

# https://www.askapache.com/online-tools/htpasswd-generator/
[web]
address = ":8080"
[web.auth.basic]
users = ["admin:$apr1$3ybtl8zp$GXOO2GpgRJAU5MRTQGQQ.1"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
  
[acme]  
email = "a.perrier89@gmail.com"  
storage = "acme.json"
entryPoint = "https"
OnHostRule = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false