defaultEntryPoints = ["http"]

# Generate Hash: https://www.askapache.com/online-tools/htpasswd-generator/
[web]
address = ":8080"
[web.auth.basic]
users = ["admin:$apr1$3ybtl8zp$GXOO2GpgRJAU5MRTQGQQ.1"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    # [entryPoints.http.redirect]
    # entryPoint = "https"
    # [entryPoints.https]
    # address = ":443"
    #     [entryPoints.https.tls]
    #         [[entryPoints.https.tls.certificates]]
    #         certFile = "examples/traefik.crt"
    #         keyFile = "examples/traefik.key"
  
# [acme]  
# email = "admin@aurelienperrier.com"  
# storage = "acme.json"
# dnsProvider = "cloudflare"
# delayDontCheckDNS = 0
# caServer = "http://172.18.0.1:4000/directory"
# entryPoint = "https"
# [[acme.domains]]
#   main = "aurelienperrier.com"
#   sans = ["drone.aurelienperrier.com"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
# swarmmode = true